In [1]:
import pandas as pd
import sqlite3

In [5]:
df = pd.read_csv('./data/vendas.csv')
df.head()

   id_venda vendedor regiao produto  data_venda  valor
0         1      Ana    Sul       A  2024-01-01    100
1         2      Ana    Sul       B  2024-01-02    200
2         3      Ana    Sul       A  2024-01-03    150
3         4    Bruno  Norte       A  2024-01-01    300
4         5    Bruno  Norte       B  2024-01-03    100

In [6]:
connection = sqlite3.connect("./db/vendas.db")
crsr = connection.cursor()
print("Connected to the database")

Connected to the database

In [7]:
df.to_sql('vendas', connection, if_exists='replace', index=False)
print("DataFrame inserted into the database")

DataFrame inserted into the database

In [ ]:
'''Mostre todas as vendas com uma coluna extra:
total de vendas por vendedor
(SUM com OVER)'''
sql_query = """ SELECT *, SUM(valor) OVER(PARTITION BY vendedor) AS total_vendas_por_vendedor
FROM vendas;"""

df_total_vendas = pd.read_sql_query(sql_query, connection)
df_total_vendas.head(10)

,id_venda,vendedor,regiao,produto,data_venda,valor,total_vendas_por_vendedor
0,1,Ana,Sul,A,2024-01-01,100,850
1,2,Ana,Sul,B,2024-01-02,200,850
2,3,Ana,Sul,A,2024-01-03,150,850
3,10,Ana,Sul,B,2024-01-06,400,850
4,4,Bruno,Norte,A,2024-01-01,300,600
5,5,Bruno,Norte,B,2024-01-03,100,600
6,6,Bruno,Norte,A,2024-01-04,200,600
7,7,Carla,Sul,A,2024-01-02,250,650
8,8,Carla,Sul,B,2024-01-03,300,650
9,9,Carla,Sul,A,2024-01-05,100,650

In [ ]:
'''Mostre o valor de cada venda e o valor médio por região'''

sql_query = """SELECT id_venda, vendedor, regiao, valor, AVG(valor) OVER( PARTITION BY regiao) AS media_vendas_por_regiao
FROM vendas;"""

df_media_vendas_por_regiao = pd.read_sql_query(sql_query, connection)
df_media_vendas_por_regiao.head(10)

   id_venda vendedor regiao  valor  media_vendas_por_regiao
0         4    Bruno  Norte    300               200.000000
1         5    Bruno  Norte    100               200.000000
2         6    Bruno  Norte    200               200.000000
3         1      Ana    Sul    100               214.285714
4         2      Ana    Sul    200               214.285714
5         3      Ana    Sul    150               214.285714
6         7    Carla    Sul    250               214.285714
7         8    Carla    Sul    300               214.285714
8         9    Carla    Sul    100               214.285714
9        10      Ana    Sul    400               214.285714

In [ ]:
'''quantidade de vendas feitas pelo mesmo vendedor'''
sql_query = """ SELECT *, COUNT(id_venda) OVER(PARTITION BY vendedor) AS total_vendas_por_vendedor
FROM vendas;"""

df_total_vendas_por_vendedor = pd.read_sql_query(sql_query, connection)
df_total_vendas_por_vendedor.head(10)

,id_venda,vendedor,regiao,produto,data_venda,valor,total_vendas_por_vendedor
0,1,Ana,Sul,A,2024-01-01,100,4
1,2,Ana,Sul,B,2024-01-02,200,4
2,3,Ana,Sul,A,2024-01-03,150,4
3,10,Ana,Sul,B,2024-01-06,400,4
4,4,Bruno,Norte,A,2024-01-01,300,3
5,5,Bruno,Norte,B,2024-01-03,100,3
6,6,Bruno,Norte,A,2024-01-04,200,3
7,7,Carla,Sul,A,2024-01-02,250,3
8,8,Carla,Sul,B,2024-01-03,300,3
9,9,Carla,Sul,A,2024-01-05,100,3

In [ ]:
'''total de vendas por região'''
sql_query = """SELECT id_venda, vendedor, regiao, valor, SUM(valor) OVER( PARTITION BY regiao) AS total_vendas_por_regiao
FROM vendas;"""

df_total_vendas_por_regiao = pd.read_sql_query(sql_query, connection)
df_total_vendas_por_regiao.head(10)

   id_venda vendedor regiao  valor  total_vendas_por_regiao
0         4    Bruno  Norte    300                      600
1         5    Bruno  Norte    100                      600
2         6    Bruno  Norte    200                      600
3         1      Ana    Sul    100                     1500
4         2      Ana    Sul    200                     1500
5         3      Ana    Sul    150                     1500
6         7    Carla    Sul    250                     1500
7         8    Carla    Sul    300                     1500
8         9    Carla    Sul    100                     1500
9        10      Ana    Sul    400                     1500

In [ ]:
'''valor máximo vendido por vendedor'''
sql_query = """SELECT id_venda, vendedor, regiao, valor, MAX(valor) OVER( PARTITION BY vendedor) AS max_venda_por_vendedor
FROM vendas;"""

df_max_venda_por_vendedor = pd.read_sql_query(sql_query, connection)
df_max_venda_por_vendedor.head(10)

   id_venda vendedor regiao  valor  max_venda_por_vendedor
0         1      Ana    Sul    100                     400
1         2      Ana    Sul    200                     400
2         3      Ana    Sul    150                     400
3        10      Ana    Sul    400                     400
4         4    Bruno  Norte    300                     300
5         5    Bruno  Norte    100                     300
6         6    Bruno  Norte    200                     300
7         7    Carla    Sul    250                     300
8         8    Carla    Sul    300                     300
9         9    Carla    Sul    100                     300

In [ ]:
'''valor mínimo vendido por região'''
sql_query = """SELECT id_venda, vendedor, regiao, valor, MIN(valor) OVER( PARTITION BY regiao) AS min_venda_por_regiao
FROM vendas;"""

df_min_venda_por_regiao = pd.read_sql_query(sql_query, connection)
df_min_venda_por_regiao.head(10)

   id_venda vendedor regiao  valor  min_venda_por_regiao
0         4    Bruno  Norte    300                   100
1         5    Bruno  Norte    100                   100
2         6    Bruno  Norte    200                   100
3         1      Ana    Sul    100                   100
4         2      Ana    Sul    200                   100
5         3      Ana    Sul    150                   100
6         7    Carla    Sul    250                   100
7         8    Carla    Sul    300                   100
8         9    Carla    Sul    100                   100
9        10      Ana    Sul    400                   100

In [ ]:
'''diferença entre o valor de cada venda e a média de vendas por vendedor'''
sql_query = """SELECT id_venda, vendedor, regiao, valor, avg(valor) OVER( PARTITION BY vendedor) AS avg_venda_por_vendedor, valor - AVG(valor) OVER(PARTITION BY vendedor) AS diferenca_media_venda_por_vendedor
FROM vendas;"""

df_diferenca_media_por_vendedor = pd.read_sql_query(sql_query, connection)
df_diferenca_media_por_vendedor.head(10)

'''positivo → acima da média
negativo → abaixo da média'''

,id_venda,vendedor,regiao,valor,avg_venda_por_vendedor,diferenca_media_venda_por_vendedor
0,1,Ana,Sul,100,212.500000,-112.500000
1,2,Ana,Sul,200,212.500000,-12.500000
2,3,Ana,Sul,150,212.500000,-62.500000
3,10,Ana,Sul,400,212.500000,187.500000
4,4,Bruno,Norte,300,200.000000,100.000000
5,5,Bruno,Norte,100,200.000000,-100.000000
6,6,Bruno,Norte,200,200.000000,0.000000
7,7,Carla,Sul,250,216.666667,33.333333
8,8,Carla,Sul,300,216.666667,83.333333
9,9,Carla,Sul,100,216.666667,-116.666667

In [ ]:
'''soma acumulada de vendas por vendedor ao longo do tempo'''
sql_query = """SELECT id_venda, data_venda, vendedor, regiao, valor, SUM(valor) OVER( PARTITION BY vendedor ORDER BY data_venda ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS acumulo_vendas_por_vendedor
FROM vendas;"""

df_acumulo_vendas_por_vendedor = pd.read_sql_query(sql_query, connection)
df_acumulo_vendas_por_vendedor.head(10)

   id_venda  data_venda vendedor regiao  valor  acumulo_vendas_por_vendedor
0         1  2024-01-01      Ana    Sul    100                          100
1         2  2024-01-02      Ana    Sul    200                          300
2         3  2024-01-03      Ana    Sul    150                          450
3        10  2024-01-06      Ana    Sul    400                          850
4         4  2024-01-01    Bruno  Norte    300                          300
5         5  2024-01-03    Bruno  Norte    100                          400
6         6  2024-01-04    Bruno  Norte    200                          600
7         7  2024-01-02    Carla    Sul    250                          250
8         8  2024-01-03    Carla    Sul    300                          550
9         9  2024-01-05    Carla    Sul    100                          650

In [ ]:
'''média móvel de 2 vendas por vendedor'''
sql_query = """SELECT id_venda, data_venda, vendedor, regiao, valor, AVG(valor) OVER( PARTITION BY vendedor ORDER BY data_venda ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS moving_average_por_vendedor
FROM vendas;"""

df_moving_average_por_vendedor = pd.read_sql_query(sql_query, connection)
df_moving_average_por_vendedor.head(10)

   id_venda  data_venda vendedor regiao  valor  moving_average_por_vendedor
0         1  2024-01-01      Ana    Sul    100                   100.000000
1         2  2024-01-02      Ana    Sul    200                   150.000000
2         3  2024-01-03      Ana    Sul    150                   150.000000
3        10  2024-01-06      Ana    Sul    400                   250.000000
4         4  2024-01-01    Bruno  Norte    300                   300.000000
5         5  2024-01-03    Bruno  Norte    100                   200.000000
6         6  2024-01-04    Bruno  Norte    200                   200.000000
7         7  2024-01-02    Carla    Sul    250                   250.000000
8         8  2024-01-03    Carla    Sul    300                   275.000000
9         9  2024-01-05    Carla    Sul    100                   216.666667

In [ ]:
'''percentual que cada venda representa do total'''
sql_query = """SELECT id_venda, vendedor, regiao, valor, SUM(valor) OVER( PARTITION BY vendedor) AS total_venda_por_vendedor, valor * 1.0 / SUM(valor) OVER(PARTITION BY vendedor) AS percentual_total_venda_por_vendedor
FROM vendas;"""

df_percentual_total_venda_por_vendedor = pd.read_sql_query(sql_query, connection)
df_percentual_total_venda_por_vendedor.head(10)

,id_venda,vendedor,regiao,valor,total_venda_por_vendedor,percentual_total_venda_por_vendedor
0,1,Ana,Sul,100,850,0.117647
1,2,Ana,Sul,200,850,0.235294
2,3,Ana,Sul,150,850,0.176471
3,10,Ana,Sul,400,850,0.470588
4,4,Bruno,Norte,300,600,0.500000
5,5,Bruno,Norte,100,600,0.166667
6,6,Bruno,Norte,200,600,0.333333
7,7,Carla,Sul,250,650,0.384615
8,8,Carla,Sul,300,650,0.461538
9,9,Carla,Sul,100,650,0.153846

In [43]:
connection.close()
print("Connection closed")

Connection closed