### Cleaning Data - Top 20 highest-grossing tours by women of all time

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/data.csv')
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [3]:
print(f'Dataframe shape: {df.shape}')
print(f'Number of missing values:\n{df.isnull().sum()}')

Dataframe shape: (20, 11)
Number of missing values:
Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [4]:
df.dtypes

Rank                                 int64
Peak                                object
All Time Peak                       object
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
Ref.                                object
dtype: object

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.columns.to_list()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [7]:
df.columns = df.columns.str.strip().str.lower().str.replace('\xa0', ' ').str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [8]:
dirty_columns = ['peak', 'all_time_peak','tour_title']
for col in dirty_columns:
  df[col] = df[col].str.replace(r'\[[^\]]*\]|[†‡*]', '', regex=True)

money_columns = ['actual_gross', 'adjusted_gross_in_2022_dollars', 'average_gross']
for col in money_columns:
  df[col] = df[col].str.replace(',', '').str.replace('$', '')

df['ref.'] = df['ref.'].str.replace('[', '').str.replace(']', '')
df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,1
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,3
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,6
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,7
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,8

In [9]:

integer_columns = ['peak', 'all_time_peak', 'ref.']
for col in integer_columns:
  df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

float_columns = ['actual_gross', 'adjusted_gross_in_2022_dollars', 'average_gross']
for col in float_columns:
  df[col] = pd.to_numeric(df[col], errors='coerce').astype(float)

df.dtypes

rank                                int64
peak                                Int64
all_time_peak                       Int64
actual_gross                      float64
adjusted_gross_in_2022_dollars    float64
artist                             object
tour_title                         object
years                              object
shows                               int64
average_gross                     float64
ref.                                Int64
dtype: object

In [10]:
df['start_year'] = df['years'].str.split('–').str[0].str.strip()
df['end_year'] = df['years'].str.split('–').str[1].str.strip().fillna(df['start_year'])
df['tour_duration'] = df['end_year'].astype(int) - df['start_year'].astype(int) + 1
df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref.,start_year,end_year,tour_duration
0,1,1,2,780000000.0,780000000.0,Taylor Swift,The Eras Tour,2023–2024,56,13928571.0,1,2023,2024,2
1,2,1,7,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0,3,2023,2023,1
2,3,1,2,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294.0,6,2008,2009,2
3,4,2,10,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795.0,7,2018,2019,2
4,5,2,<NA>,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0,8,2018,2018,1

In [11]:
df.isnull().sum()

rank                               0
peak                              11
all_time_peak                     14
actual_gross                       2
adjusted_gross_in_2022_dollars     0
artist                             0
tour_title                         0
years                              0
shows                              0
average_gross                      0
ref.                               1
start_year                         0
end_year                           0
tour_duration                      0
dtype: int64

In [12]:
df.head(20)

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref.,start_year,end_year,tour_duration
0,1,1,2,780000000.0,780000000.0,Taylor Swift,The Eras Tour,2023–2024,56,13928571.0,1,2023,2024,2
1,2,1,7,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0,3,2023,2023,1
2,3,1,2,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294.0,6,2008,2009,2
3,4,2,10,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795.0,7,2018,2019,2
4,5,2,<NA>,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0,8,2018,2018,1
5,6,2,10,305158363.0,388978496.0,Madonna,The MDNA Tour,2012,88,3467709.0,9,2012,2012,1
6,7,2,<NA>,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405.0,11,2008,2009,2
7,7,<NA>,<NA>,257600000.0,257600000.0,Pink,Summer Carnival,2023–2024,41,6282927.0,12,2023,2024,2
8,9,<NA>,<NA>,256084556.0,312258401.0,Beyoncé,The Formation World Tour,2016,49,5226215.0,13,2016,2016,1
9,10,<NA>,<NA>,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,2015,85,2945882.0,14,2015,2015,1
10,11,<NA>,<NA>,NaN,283202896.0,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606.0,1516,2013,2014,2
11,12,<NA>,14,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227.0,18,2009,2011,3
12,13,<NA>,<NA>,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,2014–2015,151,1350993.0,19,2014,2015,2
13,14,1,<NA>,200000000.0,299676265.0,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385.0,20,2002,2005,4
14,15,2,<NA>,194000000.0,281617035.0,Madonna,Confessions Tour,2006,60,3233333.0,5,2006,2006,1
15,16,<NA>,<NA>,184000000.0,227452347.0,Pink,The Truth About Love Tour,2013–2014,142,1295775.0,22,2013,2014,2
16,17,<NA>,<NA>,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,2012–2013,98,1734694.0,<NA>,2012,2013,2
17,18,<NA>,<NA>,169800000.0,207046755.0,Madonna,Rebel Heart Tour,2015–2016,82,2070732.0,4,2015,2016,2
18,19,<NA>,<NA>,NaN,204486106.0,Adele,Adele Live 2016,2016–2017,121,1385950.0,25,2016,2017,2
19,20,<NA>,<NA>,150000000.0,185423109.0,Taylor Swift,The Red Tour,2013–2014,86,1744186.0,26,2013,2014,2

*Valores ausentes em `actual_gross` e parte de `peak` foram preenchidos manualmente utilizando a mesma fonte original do dataset: [Wikipedia](https://en.wikipedia.org/wiki/List_of_highest-grossing_concert_tours_by_women#All-time_ranking).*

*A coluna `all_time_peak` não foi totalmente imputada, pois esse ranking foi posteriormente descontinuado pela própria página. Versões históricas da página também apresentavam diversos valores ausentes, indicando que a ausência desses dados é estrutural e não um erro de coleta.*

In [13]:

Adele_tour = df[df['tour_title'].str.contains('Adele Live 2016')]
df.loc[Adele_tour.index, 'actual_gross'] = 16770000.0
Mrs_carter_tour = df[df['tour_title'].str.contains('The Mrs. Carter Show World Tour')]
df.loc[Mrs_carter_tour.index, 'actual_gross'] = 22970000.0
df.loc[Mrs_carter_tour.index, 'peak'] = 5

In [14]:

Summer_carnival_tour = df[df['tour_title'].str.contains('Summer Carnival')]
df.loc[Summer_carnival_tour.index, 'peak'] = 2
df.loc[Summer_carnival_tour.index, 'rank'] = 8
Formation_tour = df[df['tour_title'].str.contains('The Formation World Tour')]
df.loc[Formation_tour.index, 'peak'] = 4
The_1989_tour = df[df['tour_title'].str.contains('The 1989 World Tour')]
df.loc[The_1989_tour.index, 'peak'] = 4
Monster_ball_tour = df[df['tour_title'].str.contains('The Monster Ball Tour')]
df.loc[Monster_ball_tour.index, 'peak'] = 4

In [15]:
df.drop(columns=['all_time_peak', 'ref.'], inplace=True)

In [16]:
df.isnull().sum()

rank                              0
peak                              6
actual_gross                      0
adjusted_gross_in_2022_dollars    0
artist                            0
tour_title                        0
years                             0
shows                             0
average_gross                     0
start_year                        0
end_year                          0
tour_duration                     0
dtype: int64

In [17]:
df.to_csv('./data/cleaned_data.csv', index=False)